version: '3'
services:
    calc:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Calculator
        ports:
            - 13337:13337
        restart: on-failure