version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - project_symfony

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - project_symfony

    # Symfony apache project container
    www:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: symfony
        ports:
          - "80:80"
        volumes:
            - ./src:/var/www
        restart: always
        networks:
            - project_symfony

networks:
    project_symfony:

volumes:
    db-data: